---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: production
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      name: Deploy
      labels:
        environment: production
    spec:
      containers:
        - name: jenkins-container
          image: vijendaraws/spc_dockerhub:1
          ports:
            - containerPort: 8080
              protocol: TCP 

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  selector:
    environment: production
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
