apiVersion: v1
kind: Pod
metadata:
  name: springpet
  labels:
    name: spc
spec:
  containers:
    - name: spc-container
      image: vijendaraws/spc_dockerhub:1
      ports:
        - name: app
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: port-service
  labels:
    name: spc
spec:
  type: NodePort
  selector:
    name: spc-container
  ports:
    - nodePort: 32516
      port: 8080
      targetPort: 8080
